# Generated by Django 2.1.7 on 2019-03-13 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['date_collected']},
        ),
    ]
