# Generated by Django 2.1.7 on 2019-06-12 20:59
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("air_quality", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="sessiondata",
            name="upload_gps",
            field=models.FileField(blank=True, null=True, upload_to="session_gps_data"),
        )
    ]
