# Generated by Django 2.1.10 on 2019-07-31 03:47
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("air_quality", "0006_auto_20190726_1709")]

    operations = [
        migrations.AlterField(
            model_name="collectionfile",
            name="processed_at",
            field=models.DateTimeField(auto_now_add=True),
        )
    ]
