# Generated by Django 2.1.11 on 2019-10-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality', '0008_auto_20190922_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionfile',
            name='processed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='collectionfile',
            name='processor_version',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
