# Generated by Django 3.0.3 on 2020-04-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality', '0009_auto_20191009_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='unit',
            field=models.CharField(choices=[('mg/m3', 'mg/m3'), ('ppm', 'ppm'), ('g/m3', 'g/m3'), ('PM10', 'PM10'), ('PM2.5', 'PM2.5'), ('μg/m3', 'μg/m3'), ('lonlat', 'lonlat')], help_text='Measurement unit, e.g., mg/m3, ppm, etc.', max_length=256),
        ),
    ]
